name: PvPArena
version: '${project.version}'
main: me.ilciab.pvparena.Main
api-version: '1.21'
author: ilciab

commands:
  fight:
    description: Your description
    usage: /fight <player>

permissions:
  fight.use:
    description: Allows players to start a fight.
    default: op